/*
 * DO NOT MODIFY. This file is automatically generated during the pre-build
 *                step by the lib_search utility
 */

"C:\git\ble_sdk\source\ti\blestack\blelib\ctrl\cc2640_hci_pxxx_sc.a"
"C:\git\ble_sdk\source\ti\blestack\blelib\ctrl\cc2640_ll_pxxx_sc.a"
"C:\git\ble_sdk\source\ti\blestack\blelib\hci_tl\cc26xx_hci_tl_none.a"
"C:\git\ble_sdk\source\ti\blestack\blelib\host\cc26xx_att_pxxx_sc.a"
"C:\git\ble_sdk\source\ti\blestack\blelib\host\cc26xx_gap_pxxx_sc.a"
"C:\git\ble_sdk\source\ti\blestack\blelib\host\cc26xx_gatt_pxxx_sc.a"
"C:\git\ble_sdk\source\ti\blestack\blelib\host\cc26xx_l2cap_pxxx_sc.a"
"C:\git\ble_sdk\source\ti\blestack\blelib\host\cc26xx_profiles_pxxx_sc.a"
"C:\git\ble_sdk\source\ti\blestack\blelib\host\cc26xx_smp_pxxx_sc.a"
"C:\git\ble_sdk\source\ti\blestack\blelib\host\cc26xx_sm_pxxx_sc.a"
