/*
 * DO NOT MODIFY. This file is automatically generated during the pre-build
 *                step by the lib_search utility
 */

"C:\ti\simplelink_cc2640r2_sdk_1_40_00_45\source\ti\blestack\blelib\ctrl\cc2640_hci_pxxo.a"
"C:\ti\simplelink_cc2640r2_sdk_1_40_00_45\source\ti\blestack\blelib\ctrl\cc2640_ll_pxxo.a"
"C:\ti\simplelink_cc2640r2_sdk_1_40_00_45\source\ti\blestack\blelib\hci_tl\cc26xx_hci_tl_none.a"
"C:\ti\simplelink_cc2640r2_sdk_1_40_00_45\source\ti\blestack\blelib\host\cc26xx_att_pxxo.a"
"C:\ti\simplelink_cc2640r2_sdk_1_40_00_45\source\ti\blestack\blelib\host\cc26xx_gap_pxxo.a"
"C:\ti\simplelink_cc2640r2_sdk_1_40_00_45\source\ti\blestack\blelib\host\cc26xx_gatt_pxxo.a"
"C:\ti\simplelink_cc2640r2_sdk_1_40_00_45\source\ti\blestack\blelib\host\cc26xx_l2cap_pxxo.a"
"C:\ti\simplelink_cc2640r2_sdk_1_40_00_45\source\ti\blestack\blelib\host\cc26xx_profiles_pxxo.a"
"C:\ti\simplelink_cc2640r2_sdk_1_40_00_45\source\ti\blestack\blelib\host\cc26xx_smp_pxxo.a"
"C:\ti\simplelink_cc2640r2_sdk_1_40_00_45\source\ti\blestack\blelib\host\cc26xx_sm_pxxo.a"
