/******************************************************************************

@file  Codec1.h

@brief This file contains the ADPCM codec functions.

Group: WCS, BTS
Target Device: cc23xx

******************************************************************************

 Copyright (c) 2022-2025, Texas Instruments Incorporated
 All rights reserved.

 Redistribution and use in source and binary forms, with or without
 modification, are permitted provided that the following conditions
 are met:

 *  Redistributions of source code must retain the above copyright
    notice, this list of conditions and the following disclaimer.

 *  Redistributions in binary form must reproduce the above copyright
    notice, this list of conditions and the following disclaimer in the
    documentation and/or other materials provided with the distribution.

 *  Neither the name of Texas Instruments Incorporated nor the names of
    its contributors may be used to endorse or promote products derived
    from this software without specific prior written permission.

 THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,
 THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
 PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR
 CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
 EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
 PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
 OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
 WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
 OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
 EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

 ******************************************************************************

 Copyright (c) 2022-2025, Texas Instruments Incorporated
 All rights reserved.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

 http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.

 ******************************************************************************
 *****************************************************************************/

#ifndef ti_adpcm_Codec1__include
#define ti_adpcm_Codec1__include

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

/*!
 *  @brief  This routine encodes one int16 sample with TI Codec Type 1.
 *
 *  @param  audSample  The audtion sample to encode
 *
 *  @return The encoded result as a 4-bit nibble
 */
extern uint8_t Codec1_encodeSingle(int16_t audSample);


/*!
 *  @brief  This routine decode a 4-bit nibble sample to a uint16 PCM audio sample.
 *
 *  @param  nibble_4bits  A 4-bit nibble to decode
 *
 *  @return The decoded value as a 16-bit PCM sample
 */
extern int16_t Codec1_decodeSingle(uint8_t nibble_4bits);

/*!
 *  @brief  This routine encode a buffer with TI codec Type 1.
 *
 *  @param  dst Pointer to the buffer where encoding result will be written to
 *
 *  @param  src Pointer to the buffer that should be encoded.
 *              Must be a multiple of 4 bytes
 *
 *  @param  srcSize The number of samples (int16) in the src buffer.
 *                  Must be a multiple of 2.
 *
 *  @param  si Pointer to the current step index
 *
 *  @param  pv Pointer to the current predicted-value
 *
 *  @return Number of bytes written to the destination buffer
 */
extern uint8_t Codec1_encodeBuff(uint8_t* dst, int16_t* src, int16_t srcSize, int8_t *si, int16_t *pv);

/*!
 *  @brief  This routine decodes a buffer with TI codec Type 1.
 *
 *  @param  dst Pointer to the buffer where decoded result will be written to
 *
 *  @param  src Pointer to the buffer that should be decoded.
 *              Must be a multiple of 4 bytes
 *
 *  @param  srcSize Number of byte that will be generated by
 *                  the encoder (4* (src buffer size in byte))
 *
 *  @param  si Pointer to the current step index
 *
 *  @param  pv Pointer to the current predicted-value
 */
extern void Codec1_decodeBuff(int16_t* dst, uint8_t* src, unsigned srcSize,  int8_t *si, int16_t *pv);

#ifdef __cplusplus
}
#endif

#endif /* ti_adpcm_Codec1__include */
/*! @}*/
