/*
 * DO NOT MODIFY. This file is automatically generated during the pre-build
 *                step by the lib_search utility
 */

"C:\TI\simplelink\ble_sdk_2_02_00_29\blelib\host\host_xcxx.a"
"C:\TI\simplelink\ble_sdk_2_02_00_29\blelib\ctrl\cc2640\cc2640_ctrl_xcxx.a"
"C:\TI\simplelink\ble_sdk_2_02_00_29\blelib\hci_tl\cc26xx\cc26xx_hci_tl_none.a"
