/*
 * DO NOT MODIFY. This file is automatically generated during the pre-build
 *                step by the lib_search utility
 */

"C:\ti\simplelink_cc2640r2_sdk_4_10_00_10\source\ti\blestack\blelib\ctrlll\cc2640_ctrlll_pxxx.a"
"C:\ti\simplelink_cc2640r2_sdk_4_10_00_10\source\ti\blestack\blelib\ctrlhci\cc2640_ctrlhci_pxxx.a"
"C:\ti\simplelink_cc2640r2_sdk_4_10_00_10\source\ti\blestack\blelib\hci_tl\cc26xx_hci_tl_none.a"
"C:\ti\simplelink_cc2640r2_sdk_4_10_00_10\source\ti\blestack\blelib\host\cc26xx_att_pxxx.a"
"C:\ti\simplelink_cc2640r2_sdk_4_10_00_10\source\ti\blestack\blelib\host\cc26xx_gap_pxxx.a"
"C:\ti\simplelink_cc2640r2_sdk_4_10_00_10\source\ti\blestack\blelib\host\cc26xx_gatt_pxxx.a"
"C:\ti\simplelink_cc2640r2_sdk_4_10_00_10\source\ti\blestack\blelib\host\cc26xx_l2cap_pxxx.a"
"C:\ti\simplelink_cc2640r2_sdk_4_10_00_10\source\ti\blestack\blelib\host\cc26xx_profiles_pxxx.a"
"C:\ti\simplelink_cc2640r2_sdk_4_10_00_10\source\ti\blestack\blelib\host\cc26xx_smp_pxxx.a"
"C:\ti\simplelink_cc2640r2_sdk_4_10_00_10\source\ti\blestack\blelib\host\cc26xx_sm_pxxx.a"
